### PR TITLE
Fixes to fake world

### LINKED ISSUE #504: Crash with Epic Fight
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Are you using the latest MineColonies Verison?

- [X] I am running the latest **alpha** version of MineColonies for my Minecraft version.
I am also running the latest (possible) versions of other mods that are part of my problem.

### Did you check on the Wiki? or ask on Discord?

- [X] I checked the MineColonies/Structurize [Wiki](https://wiki.minecolonies.ldtteam.com/) or I asked on [discord](https://discord.minecolonies.com/). Or I was sent from discord to open an issue here.

### Minecraft Version

1.18

### MineColonies Version

minecolonies-1.18.2-1.0.673-ALPHA

### Structurize Version

structurize-1.18.2-1.0.389-RELEASE

### Related Mods and their Versions

Forge 40.1.0

### Reproduction Steps

Hello, I'm a creator of Epic Fight and I've got a crash report that conflicts with MineColonies. the direct reason for the crash is this:

```
Caused by: java.lang.NullPointerException: Cannot invoke "net.minecraft.world.level.GameRules.getBoolean(net.minecraft.world.level.GameRules$Key)" because the return value of "net.minecraft.world.level.Level.getGameRules()" is null
```

So, I wonder if MineColonies creates a level instance that returns a null value for getGameRules() method. If there's a reason it should be a null value, I'll just check if it is null before executing my code. Thanks.

The original page for this report is here: https://github.com/Yesssssman/epicfightmod/issues/990

### Logs

https://gist.github.com/Yesssssman/b384facc0a6041618bb66b3f293839ad

### Anything else?

_No response_

### Footer

---
## Viewers
* Add a thumbs-up to the bug report if you are also affected. This helps the bug report become more visible to the team and doesn't clutter the comments.
* Add a comment if you have any insights or background information that isn't already part of the conversation.

### PR DESCRIPTION
**Pull request by Nightenom**
Closes #504 
Progress towards #489 

# Changes proposed in this pull request:
- bump gradle and forge versions (min forge is recommended build)
- update fake world and chunk classes
- make substitution blocks smarter in c6155de8efa844e44afd801eca7b8c7b0c163d91
- preview will now respect surrounding biomes in full update (after rotate/mirror change)
- general cleanup removing most warnings (just 2 deprecations left)

Review please

### CODE REVIEW

File: src/main/java/com/ldtteam/structurize/placement/structure/CreativeStructureHandler.java [hunk 1]
```diff
@@ -140,6 +140,12 @@ public void prePlacementLogic(final BlockPos worldPos, final BlockState blockSta
...
     {
-        return BlockUtils.getSubstitutionBlockAtWorld(getWorld(), worldPos);
+        return BlockUtils.getSubstitutionBlockAtWorld(getWorld(), worldPos, null);
+    }
+
+    @Override
+    public BlockState getWorldGenBlock(final BlockPos worldPos, final BlockState virtualBlockAbove)
+    {
+        return BlockUtils.getSubstitutionBlockAtWorld(getWorld(), worldPos, virtualBlockAbove);
     }
```
Comment (Raycoms) [inline src/main/java/com/ldtteam/structurize/placement/structure/CreativeStructureHandler.java:150]: I don't get why that has to be an extra method. That should just be called by the default getSolidBlockForPos behaviour, but not have to exist in all handlers.

File: src/main/java/com/ldtteam/structurize/placement/structure/IStructureHandler.java [hunk 2]
```diff
@@ -252,5 +252,14 @@ default BlockPos getProgressPosInWorld(final BlockPos localPos)
      * @param worldPos the world pos.
      * @return the right block (classically biome dependent).
      */
+    @Deprecated(forRemoval = true, since = "1.18.2")
     BlockState getSolidBlockForPos(BlockPos worldPos);
```
Comment (Raycoms) [inline src/main/java/com/ldtteam/structurize/placement/structure/IStructureHandler.java:256]: I would keep this, so that we can still have "a block we want" and not "only worldgen block"

File: src/main/java/com/ldtteam/structurize/placement/structure/CreativeStructureHandler.java (hunk 1 above)
Comment (Nightenom) [reply src/main/java/com/ldtteam/structurize/placement/structure/CreativeStructureHandler.java:150]: name addressed, leaving the method where it is - not gonna touch tape

File: src/main/java/com/ldtteam/structurize/placement/structure/IStructureHandler.java (hunk 2 above)
Comment (Nightenom) [reply src/main/java/com/ldtteam/structurize/placement/structure/IStructureHandler.java:256]: name addressed

**Review by Nightenom — COMMENTED** [review]
tested sp and mp

**Review by Raycoms — DISMISSED** [review]
