### PR TITLE
Avoid infinite loops in falling block placement handler

### LINKED ISSUE #740: minecolonies-1.1.947-1.21.1-snapshot crash when opening 'Building options'.
### Is there an existing issue for this?

- [x] I have searched the existing issues.

### Are you using the latest Structurize Version?

- [x] I am running the latest **beta/release** version of Structurize for my Minecraft version.
I am also running the latest versions of other mods that are part of my problem.

### Did you check on the Wiki? or ask on Discord?

- [x] I checked the MineColonies/Structurize [Wiki](https://wiki.minecolonies.ldtteam.com/) or I asked on [discord](https://discord.minecolonies.com/).

### Minecraft Version

1.21

### Structurize Version

minecolonies-1.1.947-1.21.1-snapshot.jar

### MineColonies Version (if related bug)

structurize-1.0.771-1.21.1-snapshot.jar

### Related Mods and their Versions

NeoForge 1.21.1-164
minecolonies-1.1.947-1.21.1-snapshot.jar
structurize-1.0.771-1.21.1-snapshot.jar

### Current Behavior

Open 'Building Options', crash the game. Got quite a few mods involved.

Crash reports:
[crash-2025-04-29_18.59.29-client.txt](https://github.com/user-attachments/files/19961495/crash-2025-04-29_18.59.29-client.txt)
[crash-2025-04-29_19.00.17-client.txt](https://github.com/user-attachments/files/19961496/crash-2025-04-29_19.00.17-client.txt)
[crash-2025-04-29_19.00.21-client.txt](https://github.com/user-attachments/files/19961497/crash-2025-04-29_19.00.21-client.txt)
[crash-2025-04-29_18.49.02-client.txt](https://github.com/user-attachments/files/19961500/crash-2025-04-29_18.49.02-client.txt)
[crash-2025-04-29_18.49.17-client.txt](https://github.com/user-attachments/files/19961498/crash-2025-04-29_18.49.17-client.txt)
[crash-2025-04-29_18.59.25-client.txt](https://github.com/user-attachments/files/19961499/crash-2025-04-29_18.59.25-client.txt)

Crash report analysis by o4-mini-high:
1. StackOverflowError in the component-map mixins

java.lang.StackOverflowError: Unexpected error
  at ReferencePipeline.toArray(ReferencePipeline.java:622)
  …
  at PatchedDataComponentMap.handler$…restorePatch(PatchedDataComponentMap.java:609)
  at DerivedComponentMap.derive(DerivedComponentMap.java:33)
  at ItemStack.<init>(ItemStack.java:265)
  …

This infinite recursion between PatchedDataComponentMap.restorePatch(...) (from the Accessories and Lithium mixins) and DerivedComponentMap.derive(...) (from OWO) during ItemStack initialization is overflowing the stack. A nearly identical trace shows up again at 19:00:17

2. StackOverflowError in Structurize’s BlockUtils

java.lang.StackOverflowError: Unexpected error
  at BlockUtils.getItemFromBlock(BlockUtils.java:313)
  at BlockUtils.getItem(BlockUtils.java:306)
  at BlockUtils.getItemStackFromBlockState(BlockUtils.java:450)
  …

Here, getItemFromBlock(...) and getItem(...) call each other without termination, causing an endless loop in Structurize’s placement handler.

3. NullPointerException in Structurize’s Blueprint code

java.lang.NullPointerException: Cannot invoke "Level.registryAccess()" because "level" is null
  at Blueprint.setRotationMirrorRelative(Blueprint.java:653)
  at Blueprint.setRotationMirror(Blueprint.java:640)
  at WindowBuildBuilding.lambda$updateResources$6(WindowBuildBuilding.java:315)
  …

Whenever MineColonies’ build-window UI tries to rotate or mirror a blueprint before it’s been bound to a world level, level is null and causes an NPE. This repeats at 18:49:17, 18:59:29, and 19:00:21.

Root causes

    Mixin conflict between Accessories, Lithium, and OWO on Minecraft’s DataComponentMap → infinite patch/derive loop.

    Recursive bug in Structurize’s BlockUtils.getItem… methods → unbounded mutual calls.

    Missing null-check in Structurize’s Blueprint.setRotationMirrorRelative when used outside a loaded world.

### Expected Behavior

No crash.

### Reproduction Steps

Open 'Building Options', crash the game.

### Logs

https://pastebin.com/qspqmpsg

### Anything else?

One log in the pastebin, the remainder attached in the 'Current Behavior' section.

### Footer

---
## Viewers
* Add a thumbs-up to the bug report if you are also affected. This helps the bug report become more visible to the team and doesn't clutter the comments.
* Add a comment if you have any insights or background information that isn't already part of the conversation.

### PR DESCRIPTION
**Pull request by someaddons**
Closes #740

# Changes proposed in this pull request
- Avoid infinite loops in falling block placement handler

## Testing
- [ ] Yes I tested this before submitting it.
- [ ] I also did a multiplayer test.

Review please

### CODE REVIEW

File: src/main/java/com/ldtteam/structurize/placement/handlers/placement/PlacementHandlers.java [hunk 1]
```diff
@@ -249,13 +252,23 @@ public List<ItemStack> getRequiredItems(
                     posBelow = posBelow.below();
                     final boolean isFirstTest = i == 0;
                     final BlockState possibleSupport = BlockUtils.getWorldgenBlock(world, posBelow, bp -> isFirstTest ? blockState : null);
-                    if (possibleSupport != null && BlockUtils.canBlockFloatInAir(possibleSupport) && !canHandle(world, posBelow, possibleSupport))
+                    if (possibleSupport != null && BlockUtils.isAnySolid(possibleSupport) && BlockUtils.canBlockFloatInAir(possibleSupport) && !canHandle(world,
+                        posBelow,
+                        possibleSupport))
                     {
                         supportBlockState = possibleSupport;
```
Comment (Nightenom) [inline src/main/java/com/ldtteam/structurize/placement/handlers/placement/PlacementHandlers.java:259]: imho weird, the old code already guarantees: `possibleSupport` is either `DIRT` or `!canHandle(...)` => it cannot be floating, so i'm now assuming that `DIRT` somehow appeared in `FallingBlock` or `Fallable` due to mixin stuff? or am i missing sth?

Comment (MotionlessTrain) [reply src/main/java/com/ldtteam/structurize/placement/handlers/placement/PlacementHandlers.java:259]: A few mods (e.g. terrafirmacraft) change dirt to be fallable, so that could be possible

Comment (Nightenom) [reply src/main/java/com/ldtteam/structurize/placement/handlers/placement/PlacementHandlers.java:259]: Yeah, so "proper" fix for these mods would be to have more defaults possible, like stone. or dimension default block assuming it's non fallable

Comment (TommyC81) [reply src/main/java/com/ldtteam/structurize/placement/handlers/placement/PlacementHandlers.java:259]: I posted the original bug report, is there anything I can test or do to assist with finding a possible cause or contributing mod? I'm using a quite extensive modpack and so far all works well apart from this item. If it is useful or make any difference; the error occurs when opening the 'Build Options' menu, sometimes the menu opens but freezes shortly after, sometimes it doesn't open at all - maybe coincidental?

**Comment by Raycoms** [comment]
Shouldn't this be fixed if we align the checks? Doesn't our solid check also look for falling block?

-------- Original Message --------

File: src/main/java/com/ldtteam/structurize/placement/handlers/placement/PlacementHandlers.java (hunk 1 above)
Comment (someaddons) [reply src/main/java/com/ldtteam/structurize/placement/handlers/placement/PlacementHandlers.java:259]: ye its a fallback for mods doing weird stuff or using weird blocks on worldgen surface

**Comment by someaddons** [comment]
Align which checks? I added the solid check as requirement for the supporting block

**Review by Nightenom — DISMISSED** [review]

**Review by Raycoms — DISMISSED** [review]

**Comment by MotionlessTrain** [comment]
Note that in case of terrafirmacraft, cobblestone is also a falling block. So that might not work as fallback

**Comment by Raycoms** [comment]
> Note that in case of terrafirmacraft, cobblestone is also a falling block. So that might not work as fallback

Maybe we go with classic stone then ?

**Comment by MotionlessTrain** [comment]
That should work better

**Comment by TommyC81** [comment]
Has this been implemented in the 1. 21.1 version?

**Comment by TommyC81** [comment]
Thank you all, can confirm that I no longer get error, and things appear to work correctly.
