### PR TITLE
Fixes

### LINKED ISSUE #326: Cannot register second position for the scan tool if there is an interactable block in the way.
### Prerequisites 

- [x ] I am running the latest **alpha** version of Structurize for my Minecraft version.
- [ x] I checked the MineColonies/Structurize [wiki](https://wiki.minecolonies.ldtteam.com/) and made sure my issue is not covered there.
- [ x] I made sure that **this issue is not a duplicate of any existing issue.**

### Context 

- Minecraft Version:
- Structurize Version:
- MineColonies Version (if related bug):
- Related Mods and their Versions:

## Expected behavior
Scan tool, even when perform right-click on a functional block, will be prioritized over the block interraction.

## Actual behavior
Cannot register a second position, must be replaced with a normal block then right-clicked.

## Steps to reproduce the issue

1. 
2. 
3. 

### Logs

- latest.log: 
- crashlog: 

### Notes

---
## Viewers

* Add a thumbs-up to the bug report if you are also affected. This helps the bug report become more visible to the team and doesn't clutter the comments.
* Add a comment if you have any insights or background information that isn't already part of the conversation.

### LINKED ISSUE #367: Scan tool crashes when substituting a water placeholder block with kelp
### Prerequisites 

- [x] I am running the latest **alpha** version of Structurize for my Minecraft version.
- [x] I checked the MineColonies/Structurize [wiki](https://wiki.minecolonies.ldtteam.com/) and made sure my issue is not covered there.
- [x] I made sure that **this issue is not a duplicate of any existing issue.**

### Context 

- Minecraft Version: 1.16.5
- Structurize Version: 0.13.169-ALPHA

## Expected behavior

That the grass block would be replaced with kelp or an chat message saying don't do that.

## Actual behavior

Minecraft crashes.

## Steps to reproduce the issue

1. Create new superflat world in creative
2. Place a grass block on the ground.
3. With the scan tool select the region of the block that was just placed down.
4. With scan tool right click the air
5. In the scan tool GUI replace the grass block with kelp.
6. Minecraft crashes.

### Logs

- latest.log and crashlog: https://gist.github.com/dupontct/f9230dfa4db0b000b0626ef4c5b31efe

### Notes

---
## Viewers

* Add a thumbs-up to the bug report if you are also affected. This helps the bug report become more visible to the team and doesn't clutter the comments.
* Add a comment if you have any insights or background information that isn't already part of the conversation.

### LINKED ISSUE #372: Hopper is invisible when pasted into world if it was scanned while powered by a redstone signal
### Prerequisites 

- [x] I am running the latest **alpha** version of Structurize for my Minecraft version.
- [x] I checked the MineColonies/Structurize [wiki](https://wiki.minecolonies.ldtteam.com/) and made sure my issue is not covered there.
- [x] I made sure that **this issue is not a duplicate of any existing issue.**

### Context 

- Minecraft Version: 1.16.5
- Structurize Version: 0.13.171-ALPHA
- Related Mods and their Versions: Forge-36.1.17

## Expected behavior

When the schematic is pasted into the world using the creative build tool the hopper should be visible.

## Actual behavior

When the schematic is pasted into the world the hopper is not visible until a adjacent block is right clicked.

## Steps to reproduce the issue

1. Create the combination of blocks shown in the picture 
2. Using the scan tool create a schematic of the three blocks as shown 
3. Using the build tool place the structure on the surface of the world and Paste it into the world. You should now see this: 
4. Right click the stone block with a empty hand and the hopper appears. 

### Logs

- latest.log: 
- crashlog: 

### Notes

---
## Viewers

* Add a thumbs-up to the bug report if you are also affected. This helps the bug report become more visible to the team and doesn't clutter the comments.
* Add a comment if you have any insights or background information that isn't already part of the conversation.

### LINKED ISSUE #373: Cactus door/trapdoor not defined as cutout
### Prerequisites 

- [x] I am running the latest **alpha** version of Structurize for my Minecraft version.
- [x] I checked the MineColonies/Structurize [wiki](https://wiki.minecolonies.ldtteam.com/) and made sure my issue is not covered there.
- [x] I made sure that **this issue is not a duplicate of any existing issue.**

### Context 

- `Minecraft v1.16.5`
- `Structurize v0.13.171`

## Expected behavior

- The windows of the cactus door and trapdoor are transparent

## Actual behavior

- The windows of the cactus door and trapdoor are solid.

## Steps to reproduce the issue

1.  Place door
2.  Observe window

### Notes

---
## Viewers

* Add a thumbs-up to the bug report if you are also affected. This helps the bug report become more visible to the team and doesn't clutter the comments.
* Add a comment if you have any insights or background information that isn't already part of the conversation.

### PR DESCRIPTION
**Pull request by Nightenom**
Closes #326
Closes #367
Closes #372
Closes #373

# Changes proposed in this pull request:
- mitigate hopper block second block update with lazy flags by copying vanilla logic into placement handler
- fixes block render types, removed shingles/slabs/timberframes/carpets from cutout, added cactus doors to cutout, added deferred render type setup for current block registration (hate Shadow 😃)
- moved anchor setting for scan tool from right click to left click, so you can shift+right click active blocks
- added message to replacement for blocks which replacement may fail due to world context, water now properly works with waterlogged things and few others - replacing waterlogged blocks with water is now impossible and require intermediate replacing with nonwaterloggable block (builders gonna hate me 🙃 @ravenbuilder934)

Review please

### CODE REVIEW

File: src/main/java/com/ldtteam/structurize/placement/handlers/placement/PlacementHandlers.java [hunk 1]
```diff
@@ -708,11 +708,21 @@ public boolean canHandle(@NotNull final World world, @NotNull final BlockPos pos
...
           @Nullable final CompoundNBT tileEntityData,
           final boolean complete,
           final BlockPos centerPos)
         {
+            // mojang abusing lazyupdates, this modification always happens, but we need it now, not later
+            BlockState blockState = blockStateIn;
+            if (blockState.getBlock() instanceof HopperBlock)
+            {
+                boolean flag = !world.isBlockPowered(pos);
+                if (flag != blockState.get(HopperBlock.ENABLED))
```
Comment (Raycoms) [inline src/main/java/com/ldtteam/structurize/placement/handlers/placement/PlacementHandlers.java]: this should be its own handler then.

Comment (Nightenom) [reply src/main/java/com/ldtteam/structurize/placement/handlers/placement/PlacementHandlers.java]: Meh, not gonna copy entire container handler because of one block being dumb, generally we need redstone sync code which would probably fix this too

Comment (Raycoms) [reply src/main/java/com/ldtteam/structurize/placement/handlers/placement/PlacementHandlers.java]: well, you can extend and override it.

Comment (Nightenom) [reply src/main/java/com/ldtteam/structurize/placement/handlers/placement/PlacementHandlers.java]: Pff, k

**Review by someaddons — APPROVED** [review]
