### PR TITLE
simplified fix

### LINKED ISSUE #580: Copper framed blocks replaced for free
### Is there an existing issue for this?

- [X] I have searched the existing issues.

### Are you using the latest Structurize Version?

- [X] I am running the latest **alpha** version of Structurize for my Minecraft version.
I am also running the latest versions of other mods that are part of my problem.

### Did you check on the Wiki? or ask on Discord?

- [X] I checked the MineColonies/Structurize [Wiki](https://wiki.minecolonies.ldtteam.com/) or I asked on [discord](https://discord.minecolonies.com/).

### Minecraft Version

1.19

### Structurize Version

1.19.2-10.491-alpha

### MineColonies Version (if related bug)

1.19.2-10.405

### Related Mods and their Versions

1. 43.2.0 Forge
2. no idea what you mean by block UI mod, JEI's version is 11.6.0.1105
3. 1.19-1.0.83 ALPHA

### Current Behavior

When building in the steampunk style, builders will replace any framed copper blocks with exposed (or more eroded copper types) framed blocks for entirely free, as long as the block was previously placed down before

they will not request these blocks

i can confirm this because i did not make exposed copper framed blocks, yet they were placed at my builders hut

### Expected Behavior

the builder would request exposed copper framed blocks, and use them to replace the old blocks

### Reproduction Steps

Make any building that uses framed copper blocks
Supply it with the needed materials (dont use creative quick build)
let the builder make it normally
repeat this until the building is at a level it requires framed exposed copper blocks
upgrade it, but do not give the builder any exposed copper framed blocks
wait and watch

### Logs

N/A

### Anything else?

example of what i mean by framed copper and framed exposed blocks

### Footer

---
## Viewers
* Add a thumbs-up to the bug report if you are also affected. This helps the bug report become more visible to the team and doesn't clutter the comments.
* Add a comment if you have any insights or background information that isn't already part of the conversation.

### PR DESCRIPTION
**Pull request by Raycoms**
Closes #580
Closes #
Closes #

# Changes proposed in this pull request:
- This is a more simplistic solution that is less intrusive
-
-

Review please

### CODE REVIEW

File: src/main/java/com/ldtteam/structurize/placement/StructurePlacer.java [hunk 1]
```diff
@@ -399,7 +399,7 @@ public BlockPlacementResult getResourceRequirements(
     {
         final BlockState worldState = world.getBlockState(worldPos);
         boolean sameBlockInWorld = false;
-        if (worldState.getBlock() == localState.getBlock())
+        if (worldState.getBlock() == localState.getBlock() && tileEntityData != null)
```
Comment (uecasm) [inline src/main/java/com/ldtteam/structurize/placement/StructurePlacer.java]: Did you mean `== null` here?  Otherwise this looks like it will be `false` a lot more than it should, e.g. for non-DO blocks.

Comment (Raycoms) [reply src/main/java/com/ldtteam/structurize/placement/StructurePlacer.java]: yes, u are right
