### PR TITLE
Blockout/fullscreen guis

### LINKED ISSUE #238: Scissors are not working well in multi scaled guis
## Expected behavior
Multiple scissors in multiple-scaled guis work correctly

## Actual behavior
Scale attributes are not propagated to lower levels of gui, offset is sometimes badly scaled

### LINKED ISSUE #243: Can not upgrade Townhall Medival Oak Alternative too level 4.
### Prerequisites 

- [x] I am running the latest **alpha** version of MineColonies and Structurize for my Minecraft version.
- [x] I checked the MineColonies/Structurize [wiki](https://wiki.minecolonies.ldtteam.com/) and made sure my issue is not covered there.
- [x] I made sure that **this issue is not a duplicate of any existing issue.**

### Context 

- Minecraft Version: 1.16.4
- MineColonies Version: 0.13.490-ALPHA
- Structurize Version: 0.13.100-RELEASE

## Problem description

Trying to upgrade Medival Oak Alternative Townhall lvl 3 to lvl 4.
As far as I can tell, the whole build finishes, but builder does not accept that it's done.
Ends up standing in a spot waving a flower pot every time.

### Notes or related things

I have tried the following:
* Waiting a very long time (+12h) for it to just finish.
* Canceling and restarted the upgrade (many times)

* Pushing the builder to different locations.
* Teleporting the builder to different locations.
* Giving the builder more clay pots, Torches, and also another Yellow Banner as that was the last request it ever made. (ends up with 2 yellow banners left in inventory including the extra one I have after stuck.)
* Canceled the upgrade. And upgraded warehouse, witch worked fine. And then restarting Upgrade of Townhall again.
* "Repair" the Townhall back to level 3. (Successfully) And then restarting upgrade to level 4.
* Totally disabled Optifine
* Made absolutely sure that the builder is not missing anything.

Resource Scroll is emtpy. and Shows townhall4 90%
the Builders Request list is empty.

Logs:
[latest.log](https://github.com/ldtteam/minecolonies/files/5646746/latest.log)
[debug.log](https://github.com/ldtteam/minecolonies/files/5646748/debug.log)

---
## Viewers

* Add a thumbs-up to the issue to vote for it. This helps the request become more visible to the team and doesn't clutter the comments.
* Add a comment if you have any insights or background information that isn't already part of the conversation.

### LINKED ISSUE #244: Quick Guide GUI is...broken
### Prerequisites 

- [x] I am running the latest **alpha** version of MineColonies and Structurize for my Minecraft version.
- [x] I checked the MineColonies/Structurize [wiki](https://wiki.minecolonies.ldtteam.com/) and made sure my issue is not covered there.
- [x] I made sure that **this issue is not a duplicate of any existing issue.**

### Context 

- Minecraft Version: 1.16.4
- MineColonies Version: 490 alpha
- Structurize Version: 100 release
- Related Mods and their Versions: none

## Expected behavior
The quick guide, shown when you first right-click on the builder hut in a new world, would look normal.

## Actual behavior
It's distorted, the text (except for one button) is unreadable, it just looks weird in general.

## Steps to reproduce the issue

1. Start a new world
2. Start a new colony
3. Right-click the builder hut

### Logs

- latest.log: 
- crashlog: 

### Notes

---
## Viewers

* Add a thumbs-up to the bug report if you are also affected. This helps the bug report become more visible to the team and doesn't clutter the comments.
* Add a comment if you have any insights or background information that isn't already part of the conversation.

### PR DESCRIPTION
**Pull request by Nightenom**
Creates #238
Closes #238
Closes #243
Closes #244

# Changes proposed in this pull request:
- added a render type to Window XML element, default is VANILLA
- VANILLA is 320*240 px
- FIXED is always gui sized
- OVERSIZED is integer upscaling like vanilla gui size setting or downscaling to framebuffer size
- FULLSCREEN adapts to framebuffer size so it matches current window size, distortion prevented
- _VANILLA suffix blocks downscaling under 320*240px 
- fixed scissors in multi scaled environment (switched to matrixstack calculations), fixed vanilla buttons not rendering correctly for huge sizes
- fixed ZoomDragView not correctly reading pane params, and not correctly scaling some mouse methods
- added textscale, textalign and shadow to vanilla buttons, they now wrap label if needed
- added blitRepeatable method for rendering of texture with repeatable interior
- changed mouse pos args in draw methods from int to double
- @Raycoms use this ˇˇ for the broken gui in minecolonies, it should be prepared
```
<window xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="../../../../../../src/main/java/com/ldtteam/blockout/blockOut.xsd"
    pause="false" size="960 540" type="FULLSCREEN_VANILLA" lightbox="false" >

    <image source="structurize:textures/gui/background.png" size="960 540" id="guide1"/>
    <button id="confirm" pos="360 455" label="Confirm"/>
    <text id="questionmark" size="210 75" color="black" pos="80 363" textscale="0.8"/>
    <text id="arrow" size="210 75" color="black" pos="637 22" textscale="0.8"/>
    <text id="chest" size="210 75" color="black" pos="646 363" textscale="0.8"/>
</window>
```

Review please

EDIT: edited to match current PR changes

### CODE REVIEW

**Comment by Nightenom** [comment]
I'm just dumb, we can use matrix stack now for easy scissor calculation

File: src/main/java/com/ldtteam/blockout/BOScreen.java [hunk 1]
```diff
@@ -111,44 +114,49 @@ public BOScreen(final Window w)
...
+        final double guiWidth = Math.max(fbWidth, 320.0d);
+        final double guiHeight = Math.max(fbHeight, 240.0d);
 
-        ms.push();
-        ms.translate(x, y, 0);
-        window.draw(ms, mx - x, my - y);
-        ms.pop();
+        final float renderZlevel = MatrixUtils.getLastMatrixTranslateZ(ms);
+        final float oldZ = minecraft.getItemRenderer().zLevel;
+        minecraft.getItemRenderer().zLevel = renderZlevel;
```
Comment (marchermans) [inline src/main/java/com/ldtteam/blockout/BOScreen.java:132]: You need a none null check for minecraft in all this code.

File: src/main/java/com/ldtteam/blockout/BOScreen.java [hunk 2]
```diff
@@ -111,44 +114,49 @@ public BOScreen(final Window w)
...
+
+        mcScale = minecraft.mainWindow.getGuiScaleFactor();
+        renderScale = window.getRenderType().calcRenderScale(minecraft.mainWindow, window);
+
+        x = Math.floor((guiWidth - window.getWidth() * renderScale) / 2.0d);
+        y = Math.floor((guiHeight - window.getHeight() * renderScale) / 2.0d);
+
+        RenderSystem.matrixMode(GL11.GL_PROJECTION);
```
Comment (marchermans) [inline src/main/java/com/ldtteam/blockout/BOScreen.java:150]: Not sure this is needed here.

**Review by marchermans — CHANGES_REQUESTED** [review]

File: src/main/java/com/ldtteam/blockout/BOScreen.java (hunk 1 above)
Comment (Nightenom) [reply src/main/java/com/ldtteam/blockout/BOScreen.java:132]: Then `if minecraft == null return` and we do no rendering

File: src/main/java/com/ldtteam/blockout/BOScreen.java (hunk 2 above)
Comment (Nightenom) [reply src/main/java/com/ldtteam/blockout/BOScreen.java:150]: Hmm?

Comment (marchermans) [reply src/main/java/com/ldtteam/blockout/BOScreen.java:150]: It at least requires some documentation.

Comment (Nightenom) [reply src/main/java/com/ldtteam/blockout/BOScreen.java:150]: Literally basic opengl rendering setup, but ok

Comment (marchermans) [reply src/main/java/com/ldtteam/blockout/BOScreen.java:150]: No why is it here.
Mc already applies this when rendering uis
So why do you need to reset everything again?
That is what I am wondering

File: src/main/java/com/ldtteam/blockout/BOScreen.java (hunk 1 above)
Comment (marchermans) [reply src/main/java/com/ldtteam/blockout/BOScreen.java:132]: You could add that too.

File: src/main/java/com/ldtteam/blockout/BOScreen.java (hunk 2 above)
Comment (Nightenom) [reply src/main/java/com/ldtteam/blockout/BOScreen.java:150]: It's not resetting, you just replace projection with unscaled one and do the scaling in modelview stack, you can probably set this up also in modelview stack but this is way safer

Comment (Nightenom) [reply src/main/java/com/ldtteam/blockout/BOScreen.java:150]: Like you can do in modelview stack
ms.getLast.getMatrix.loadIdentity
ms.translate x y zLevel
ms.scale renderScale/mcScale
but you would need to fix scissors since they would still be in mcScale environment rather than in framebuffer scaled environment

File: src/main/java/com/ldtteam/blockout/Pane.java [hunk 3]
```diff
@@ -856,4 +876,66 @@ public void setHoverToolTip(final List<IFormattableTextComponent> lines)
...
+     * Probably only useful for textures like vanilla button.
+     */
+    protected static void blitRepeatable(final MatrixStack ms,
+        final int x, final int y, // classical start target coords [pixels]
+        final int width, final int height, // target rendering box [pixels]
+        final int u, final int v, // texture start offset [texels]
+        final int uWidth, final int vHeight, // texture rendering box [texels]
+        final int textureWidth, final int textureHeight, // texture file size [texels]
+        final int uRepeat, final int vRepeat, // offset relative to u, v [texels]
+        final int repeatWidth, final int repeatHeight) // size of repeatable box in texture [texels]
```
Comment (Raycoms) [inline src/main/java/com/ldtteam/blockout/Pane.java]: this param doc should be javadoc @param

File: src/main/java/com/ldtteam/structurize/items/ItemCaliper.java [hunk 4]
```diff
@@ -45,6 +45,8 @@ public ActionResultType onAirRightClick(final BlockPos start,
         {
             return ActionResultType.FAIL;
         }
+        // fullscreen gui test
+        // new com.ldtteam.structurize.client.gui.WindowFullscreenTest().open(); if(true)return ActionResultType.SUCCESS;
```
Comment (Raycoms) [inline src/main/java/com/ldtteam/structurize/items/ItemCaliper.java]: remove comment

File: src/main/java/com/ldtteam/blockout/views/View.java [hunk 5]
```diff
@@ -94,12 +100,12 @@ public void drawSelfLast(final MatrixStack ms, final int mx, final int my)
...
         // Translate Mouse into the View
-        final int drawX = mx - paddedX;
-        final int drawY = my - paddedY;
+        final double drawX = mx - paddedX;
+        final double drawY = my - paddedY;
 
         for (final Pane child : children)
         {
-            if (child.isVisible())
+            if (childIsVisible(child) && child.isVisible())
```
Comment (ShadowProtocol) [inline src/main/java/com/ldtteam/blockout/views/View.java:105]: A very small thing, but I had to look twice to notice that they were not the exact same condition. It might be helpful to rename the method to ``childWithinBounds`` or something?

File: src/main/java/com/ldtteam/blockout/views/ZoomDragView.java [hunk 6]
```diff
@@ -42,12 +43,12 @@ public ZoomDragView()
     public ZoomDragView(final PaneParams params)
     {
         super(params);
-        dragFactor = params.getDoubleAttribute("dragfactor", dragFactor);
-        dragEnabled = params.getBooleanAttribute("dragenabled", dragEnabled);
-        zoomFactor = params.getDoubleAttribute("zoomfactor", zoomFactor);
-        zoomEnabled = params.getBooleanAttribute("zoomenabled", zoomEnabled);
-        minScale = params.getDoubleAttribute("minscale", minScale);
-        maxScale = params.getDoubleAttribute("maxscale", maxScale);
+        dragFactor = params.getDoubleAttribute("dragFactor", dragFactor);
```
Comment (ShadowProtocol) [inline src/main/java/com/ldtteam/blockout/views/ZoomDragView.java]: Maybe (probably) its just me, but I expect all markup attributes to be in lowercase or kebab-case. To me this is less guessable. I know the standard does have them, but I haven't really seen it round too often, bar the schema one.

File: src/main/resources/assets/structurize/lang/en_us.json [hunk 7]
```diff
@@ -1151,5 +1151,7 @@
   "block.structurize.multiblock": "Multi-Piston",
   "block.structurize.horizontal_plain_cactus_birch_timber_frame": "Plain Horizontal Cactus Birch Timber Frame",
   "structurize.gui.buildtool.creative_only": "Structurize does not support using the build tool when in survival. Switch to creative or install MineColonies and use the MineColonies Builder.",
-  "structurize.gui.replaceblock.ambiguous_properties": "Transformation from %s to %s is ambiguous because the following properties are not present in the source block: %s"
+  "structurize.gui.replaceblock.ambiguous_properties": "Transformation from %s to %s is ambiguous because the following properties are not present in the source block: %s",
+  "structurize.config.excludeentities": "Entities excluded from BP rendering",
```
Comment (ShadowProtocol) [inline src/main/resources/assets/structurize/lang/en_us.json]: What's BP? Just so every user knows explicitly.

**Review by ShadowProtocol — COMMENTED** [review]
Haven't had a good study into the scissor stuff, but this looks good to me.

File: src/main/resources/assets/structurize/lang/en_us.json (hunk 7 above)
Comment (ravenbuilder934) [reply src/main/resources/assets/structurize/lang/en_us.json]: I agree, blueprint should be spelled out

```suggestion
  "structurize.config.excludeentities": "Entities Excluded from Blueprint Rendering",
```

File: src/main/resources/assets/structurize/lang/en_us.json [hunk 8]
```diff
@@ -1151,5 +1151,7 @@
...
+  "structurize.config.excludeentities.comment": "Excludes entities from blueprint rendering if they can't load on client side. If you are going to add \"minecraft\" entity or you believe it's our fault that an entity couldn't be set up, please, make an issue at our GitHub and add stacktrace to it (so we can try to fix it)."
```
Comment (ravenbuilder934) [inline src/main/resources/assets/structurize/lang/en_us.json]:
```suggestion
  "structurize.config.excludeentities.comment": "Excludes entities from blueprint rendering if they can't load clientside. If you are going to add a "\minecraft\" entity or you believe it's our fault that an entity couldn't be set up, please make an issue at our GitHub and add the stacktrace to it."
```

File: src/main/resources/assets/structurize/lang/en_us.json (hunk 7 above)
Comment (Nightenom) [reply src/main/resources/assets/structurize/lang/en_us.json]: I agree with this but the name is just long, but could not find something shorter
Feel free to suggest something completely different

File: src/main/java/com/ldtteam/blockout/views/ZoomDragView.java (hunk 6 above)
Comment (Raycoms) [reply src/main/java/com/ldtteam/blockout/views/ZoomDragView.java]: yeah, the others are maxscale so this should be dragfactor

File: src/main/resources/assets/structurize/lang/en_us.json (hunk 7 above)
Comment (Raycoms) [reply src/main/resources/assets/structurize/lang/en_us.json]: It's in the config, doesn't matter if its a bit longer

Comment (Nightenom) [reply src/main/resources/assets/structurize/lang/en_us.json]: config name is gonna be used for gui buttons, so they can't be long

File: src/main/java/com/ldtteam/blockout/views/ZoomDragView.java (hunk 6 above)
Comment (Nightenom) [reply src/main/java/com/ldtteam/blockout/views/ZoomDragView.java]: kk, gonna change the schema

File: src/main/java/com/ldtteam/blockout/views/View.java (hunk 5 above)
Comment (Nightenom) [reply src/main/java/com/ldtteam/blockout/views/View.java:105]: this mechanism probably needs a visit in the future, so can be renamed later, gonna create issue

**Review by marchermans — DISMISSED** [review]

File: src/main/java/com/ldtteam/blockout/controls/ImageRepeatable.java [hunk 9]
```diff
@@ -0,0 +1,155 @@
...
+import com.mojang.blaze3d.matrix.MatrixStack;
+import com.mojang.blaze3d.systems.RenderSystem;
+import net.minecraft.util.ResourceLocation;
+import net.minecraft.util.Tuple;
+import org.lwjgl.opengl.GL11;
+
+/**
+ * Image element with repeatable middle part.
+ */
+public class ImageRepeatable extends Pane
```
Comment (ShadowProtocol) [inline src/main/java/com/ldtteam/blockout/controls/ImageRepeatable.java:15]: Surely we can extend the Image functionality, if not integrate the two?

File: src/main/java/com/ldtteam/blockout/controls/ImageRepeatable.java [hunk 10]
```diff
@@ -0,0 +1,155 @@
...
+    {
+        super(params);
+        final String source = params.getStringAttribute("source", null);
+        if (source != null)
+        {
+            resourceLocation = new ResourceLocation(source);
+            loadMapDimensions();
+        }
+
+        PaneParams.SizePair size = params.getSizePairAttribute("uv", null, null);
```
Comment (ShadowProtocol) [inline src/main/java/com/ldtteam/blockout/controls/ImageRepeatable.java]: We should probably stick with the "imageoffset" and "imagesize" terminology for consistency. Personally I'd like to use the terms "offset" and "crop" when referring to the texture throughout all of blockout, but that's just my personal sense of clarity.

File: src/main/java/com/ldtteam/blockout/controls/ImageRepeatable.java [hunk 11]
```diff
@@ -0,0 +1,155 @@
...
+        }
+
+        size = params.getSizePairAttribute("uvBox", null, null);
+        if (size != null)
+        {
+            uWidth = size.getX();
+            vHeight = size.getY();
+        }
+
+        size = params.getSizePairAttribute("uvRepeat", null, null);
```
Comment (ShadowProtocol) [inline src/main/java/com/ldtteam/blockout/controls/ImageRepeatable.java]: just a non-critical point of discussion: could we use "slice" instead of defining a box in a box. The slice will define the number of pixels in from each edge to go to get your nine-square layout. Personally I find it more intuitive, but maybe that's because it's how I first learned tiling systems.

**Review by ShadowProtocol — COMMENTED** [review]
Just a couple of opinionated things from me, but this looks good. 
Hopefully some of my changes can make things a bit DRYer (not that they're that bad).

File: src/main/java/com/ldtteam/blockout/controls/ImageRepeatable.java (hunk 9 above)
Comment (Nightenom) [reply src/main/java/com/ldtteam/blockout/controls/ImageRepeatable.java:15]: image is scalable, this is not (or not supposed to be), so integrating can be difficult, but for sure something can be abstracted
same goes towards ButtonImage - there is a problem of having the image logic three times duplicated
leaving the decision up to you

File: src/main/java/com/ldtteam/blockout/controls/ImageRepeatable.java (hunk 10 above)
Comment (Nightenom) [reply src/main/java/com/ldtteam/blockout/controls/ImageRepeatable.java]: I would personally rename the old params, since imageOffset is more like pane offset for me
crop means something different? or I haven't seen it being used in this context

File: src/main/java/com/ldtteam/blockout/controls/ImageRepeatable.java (hunk 11 above)
Comment (Nightenom) [reply src/main/java/com/ldtteam/blockout/controls/ImageRepeatable.java]: box in box is more customizable, your slice has fixed all borders to the same size, if I get you right

File: src/main/java/com/ldtteam/blockout/controls/ImageRepeatable.java (hunk 9 above)
Comment (ShadowProtocol) [reply src/main/java/com/ldtteam/blockout/controls/ImageRepeatable.java:15]: Hmm, I think my PR will solve this anyway, it will allow for property grouping of sorts. I'll let it explain itself once I push it.

File: src/main/java/com/ldtteam/blockout/controls/ImageRepeatable.java (hunk 10 above)
Comment (ShadowProtocol) [reply src/main/java/com/ldtteam/blockout/controls/ImageRepeatable.java]: I have nothing wrong with offset personally. Could just name everything with a source prefix, i.e. ``sourcepos`` ``sourcesize``, which is the most boring but most clear for newcomers I think. Technically we are cropping out a section of the source, but you're right in that crop doesn't usually refer directly to the width and height. I have seen it used here before though, if only once. We could potentially code in a 4-hand property, e.g. ``crop="2 2 192 20"``, which is a more logical use of the word (but of course it's ambiguous whether it is point-to-point or pos and size).

I don't really mind which but I do think we should be consistent across the board.

File: src/main/java/com/ldtteam/blockout/controls/ImageRepeatable.java (hunk 11 above)
Comment (ShadowProtocol) [reply src/main/java/com/ldtteam/blockout/controls/ImageRepeatable.java]: You could have it as a pair for vertical and horizontal, or as a 4-hand property for each edge. Still my preference but I don't mind either way. I would note though that uvRepeat isn't immediately apparent of what it refers to, though I'm not sure how to make that much clearer.

File: src/main/java/com/ldtteam/blockout/controls/ImageRepeatable.java (hunk 10 above)
Comment (Nightenom) [reply src/main/java/com/ldtteam/blockout/controls/ImageRepeatable.java]: > We could potentially code in a 4-hand property, e.g. crop="2 2 192 20", which is a more logical use of the word (but of course it's ambiguous whether it is point-to-point or pos and size).

I have thought about this too, not sure if it's a good approach tho

We can also go back to traditional `textureoffset` and `texturesize`, and thus `repeatoffset `and `repeatsize`

Comment (ShadowProtocol) [reply src/main/java/com/ldtteam/blockout/controls/ImageRepeatable.java]: Yeah that's nice and clear, I like it.

File: src/main/java/com/ldtteam/blockout/controls/ImageRepeatable.java (hunk 9 above)
Comment (Nightenom) [reply src/main/java/com/ldtteam/blockout/controls/ImageRepeatable.java:15]: Marking as resolved for now

**Comment by Nightenom** [comment]
This PR is now in frozen state so it does not prevent fixes in mcol. Waiting for Shadow to do his changes and then this will get merged upstream
