### PR TITLE
fix item icon number rendering

### LINKED ISSUE #400: Structurize failing to load
### Prerequisites 

- [x] I am running the latest **alpha** version of Structurize for my Minecraft version.
- [x] I checked the MineColonies/Structurize [wiki](https://wiki.minecolonies.ldtteam.com/) and made sure my issue is not covered there.
- [x] I made sure that **this issue is not a duplicate of any existing issue.**

### Context 

- Minecraft Version: 1.16.5
- Structurize Version: 0.13.192
- MineColonies Version (if related bug): 0.14.235
- Related Mods and their Versions:

## Actual behavior

Game crashes on launch, throwing me "Structurize has failed to load correctly error
javaw_Ybwr7Og3Mb

## Steps to reproduce the issue

1. 
2. 
3. 

### Logs

- latest.log: https://gist.github.com/Kriiks/100317086447da9af998026174b960f5
- crashlog: https://gist.github.com/Kriiks/aea06e6ce9c4d54a710d4a78ae8ae426
### Notes

---
## Viewers

* Add a thumbs-up to the bug report if you are also affected. This helps the bug report become more visible to the team and doesn't clutter the comments.
* Add a comment if you have any insights or background information that isn't already part of the conversation.

### LINKED ISSUE #403: ItemIcon not scaling properly
inline with matrixstack version https://github.com/ldtteam/Structurize/blob/version/1.16.3/src/main/java/com/ldtteam/blockout/controls/ItemIcon.java#L109

### PR DESCRIPTION
**Pull request by Raycoms**
Closes #403
Closes #
Closes #

# Changes proposed in this pull request:
- Fix Item Icon number rendering
-
-

Review please

### CODE REVIEW

File: src/main/java/com/ldtteam/blockout/controls/ItemIcon.java [hunk 1]
```diff
@@ -106,13 +113,84 @@ public void drawSelf(final MatrixStack ms, final double mx, final double my)
...
             ms.popPose();
         }
     }
 
+    private void renderGuiItemDecorations(
+      final MatrixStack matrixstack,
+      final FontRenderer fontRenderer,
+      final ItemStack stack)
+    {
+        if (!stack.isEmpty())
```
Comment (Nightenom) [inline src/main/java/com/ldtteam/blockout/controls/ItemIcon.java]:
```suggestion
```
We check that in draw method

File: src/main/java/com/ldtteam/blockout/controls/ItemIcon.java [hunk 2]
```diff
@@ -106,13 +113,84 @@ public void drawSelf(final MatrixStack ms, final double mx, final double my)
...
+        {
+            if (stack.getCount() != 1)
+            {
+                String s = String.valueOf(stack.getCount());
+                matrixstack.translate(0.0D, 0.0D, mc.getItemRenderer().blitOffset + 200.0F);
```
Comment (Nightenom) [inline src/main/java/com/ldtteam/blockout/controls/ItemIcon.java]:
```suggestion
                matrixstack.translate(0.0D, 0.0D, 200.0D);
```

File: src/main/java/com/ldtteam/blockout/controls/ItemIcon.java [hunk 3]
```diff
@@ -106,13 +113,84 @@ public void drawSelf(final MatrixStack ms, final double mx, final double my)
             renderItemModelIntoGUI(itemStack,
                 ms,
                 Minecraft.getInstance().getItemRenderer().getModel(itemStack, null, Minecraft.getInstance().player));
```
Comment (Nightenom) [inline src/main/java/com/ldtteam/blockout/controls/ItemIcon.java]:
```suggestion
                mc.getItemRenderer().getModel(itemStack, null, mc.player));
```
out of changed lines but just saw that

File: src/main/java/com/ldtteam/blockout/controls/ItemIcon.java [hunk 4]
```diff
@@ -106,13 +113,84 @@ public void drawSelf(final MatrixStack ms, final double mx, final double my)
...
+                int j = stack.getItem().getRGBDurabilityForDisplay(stack);
+                fillRect(bufferbuilder,  2, 13, 13, 2, 0, 0, 0, 255);
+                fillRect(bufferbuilder, 2, 13, i, 1, j >> 16 & 255, j >> 8 & 255, j & 255, 255);
+                RenderSystem.enableBlend();
+                RenderSystem.enableAlphaTest();
+                RenderSystem.enableTexture();
+                RenderSystem.enableDepthTest();
+            }
+
+            ClientPlayerEntity clientplayerentity = Minecraft.getInstance().player;
```
Comment (Nightenom) [inline src/main/java/com/ldtteam/blockout/controls/ItemIcon.java]:
```suggestion
```

File: src/main/java/com/ldtteam/blockout/controls/ItemIcon.java [hunk 5]
```diff
@@ -106,13 +113,84 @@ public void drawSelf(final MatrixStack ms, final double mx, final double my)
...
+            float f3 = clientplayerentity == null ? 0.0F : clientplayerentity.getCooldowns().getCooldownPercent(stack.getItem(), Minecraft.getInstance().getFrameTime());
```
Comment (Nightenom) [inline src/main/java/com/ldtteam/blockout/controls/ItemIcon.java]:
```suggestion
            float f3 = mc.player == null ? 0.0F : mc.player.getCooldowns().getCooldownPercent(stack.getItem(), mc.getFrameTime());
```

File: src/main/java/com/ldtteam/blockout/controls/ItemIcon.java [hunk 6]
```diff
@@ -106,13 +113,84 @@ public void drawSelf(final MatrixStack ms, final double mx, final double my)
...
+                RenderSystem.disableDepthTest();
+                RenderSystem.disableTexture();
+                RenderSystem.disableAlphaTest();
+                RenderSystem.disableBlend();
+                Tessellator tessellator = Tessellator.getInstance();
+                BufferBuilder bufferbuilder = tessellator.getBuilder();
+                double health = stack.getItem().getDurabilityForDisplay(stack);
+                int i = Math.round(13.0F - (float) health * 13.0F);
+                int j = stack.getItem().getRGBDurabilityForDisplay(stack);
+                fillRect(bufferbuilder,  2, 13, 13, 2, 0, 0, 0, 255);
```
Comment (Nightenom) [inline src/main/java/com/ldtteam/blockout/controls/ItemIcon.java]:
```suggestion
                fill(matrixstack, 2, 13, 13, 2, 0xff000000);
```

File: src/main/java/com/ldtteam/blockout/controls/ItemIcon.java [hunk 7]
```diff
@@ -106,13 +113,84 @@ public void drawSelf(final MatrixStack ms, final double mx, final double my)
...
+                fillRect(bufferbuilder, 2, 13, i, 1, j >> 16 & 255, j >> 8 & 255, j & 255, 255);
```
Comment (Nightenom) [inline src/main/java/com/ldtteam/blockout/controls/ItemIcon.java]:
```suggestion
                fill(matrixstack, 2, 13, i, 1, 0xff000000 | j);
```

File: src/main/java/com/ldtteam/blockout/controls/ItemIcon.java [hunk 8]
```diff
@@ -106,13 +113,84 @@ public void drawSelf(final MatrixStack ms, final double mx, final double my)
...
+            float f3 = clientplayerentity == null ? 0.0F : clientplayerentity.getCooldowns().getCooldownPercent(stack.getItem(), Minecraft.getInstance().getFrameTime());
+            if (f3 > 0.0F)
+            {
+                RenderSystem.disableDepthTest();
+                RenderSystem.disableTexture();
+                RenderSystem.enableBlend();
+                RenderSystem.defaultBlendFunc();
+                Tessellator tessellator1 = Tessellator.getInstance();
+                BufferBuilder bufferbuilder1 = tessellator1.getBuilder();
+                fillRect(bufferbuilder1, 0, MathHelper.floor(16.0F * (1.0F - f3)), 16, MathHelper.ceil(16.0F * f3), 255, 255, 255, 127);
```
Comment (Nightenom) [inline src/main/java/com/ldtteam/blockout/controls/ItemIcon.java]:
```suggestion
                fill(matrixstack, 0, MathHelper.floor(16.0F * (1.0F - f3)), 16, MathHelper.ceil(16.0F * f3), 0x7fffffff);
```

File: src/main/java/com/ldtteam/blockout/controls/ItemIcon.java [hunk 9]
```diff
@@ -106,13 +113,84 @@ public void drawSelf(final MatrixStack ms, final double mx, final double my)
...
+                RenderSystem.enableTexture();
+                RenderSystem.enableDepthTest();
+            }
+        }
+    }
+
+    private void fillRect(BufferBuilder builder, int x1, int y1, int x2, int y2, int r, int g, int b, int a)
```
Comment (Nightenom) [inline src/main/java/com/ldtteam/blockout/controls/ItemIcon.java]: delete this

**Review by Nightenom — COMMENTED** [review]
yep, that's what I want 👍 
but you have to check that inlined method is using matrixstack everywhere, that's why mojang did not matrixstacked everything yet
(and we dont use blitoffset unless really needed)

**Review by Nightenom — APPROVED** [review]
If tested then merge
