### PR TITLE
1.16.5 compat and entity dupe fix

### LINKED ISSUE #264: Urgent, notify player when DFU is not present
Some mods simply remove vanilla DFU (DataFixerUpper) to save memory. 
This breaks our entire compat layer for old schematics rendering them unloadable.

Solution for client is to notify the player onWorldJoin/on old schematic being loaded and close the buildtool gui.
Server should crash during sided setup

something like this should be in DataFixerUtils
`public static boolean hasVanillaDatafixer = DataFixesManager.getDataFixer() instanceof com.mojang.datafixers.DataFixerUpper;`
<https://github.com/ldtteam/Structurize/blob/version/1.16.3/src/main/java/com/ldtteam/structures/blueprints/v1/DataFixerUtils.java>

### PR DESCRIPTION
**Pull request by Raycoms**
Closes #264
Closes #
Closes #

# Changes proposed in this pull request:
- Fix 1.16.5 compat
- Don't allow spawning living entities when not in creative mode.
-

Review please

### CODE REVIEW

**Comment by ravenbuilder934** [comment]
```java
        {
            Log.getLogger().error("----------------------------------------------------------------- \n "
                                    + "Invalid DataFixer detected, schematics might not paste correctly! \n"
                                    +  "The following DataFixer was added: " + DataFixesManager.getDataFixer().getClass() + "\n"
                                    + "-----------------------------------------------------------------");
```
Closes #264?

**Comment by Raycoms** [comment]
It does, like in desc =P

**Comment by ravenbuilder934** [comment]
Well sure now that you edited the desc :P

**Comment by Raycoms** [comment]
I had edited that before your comment! xD

**Review by Asherslab — DISMISSED** [review]

**Comment by ravenbuilder934** [comment]
but I hadn't reloaded

File: src/main/java/com/ldtteam/structures/blueprints/v1/DataVersion.java [hunk 1]
```diff
@@ -12,8 +12,9 @@
      * - successors match
      * - upcoming has data version = (latest data version + 1)
      */
-    UPCOMING(2585, null, null),
-    v1_16_4(2584, "1.16.4", UPCOMING),
+    UPCOMING(2586, null, null),
+    v1_16_5(2585, "1.16.4", UPCOMING),
```
Comment (Nightenom) [inline src/main/java/com/ldtteam/structures/blueprints/v1/DataVersion.java]:
```suggestion
    v1_16_5(2586, "1.16.5", UPCOMING),
```

File: src/main/java/com/ldtteam/structures/blueprints/v1/DataVersion.java [hunk 2]
```diff
@@ -12,8 +12,9 @@
      * - successors match
      * - upcoming has data version = (latest data version + 1)
      */
-    UPCOMING(2585, null, null),
-    v1_16_4(2584, "1.16.4", UPCOMING),
+    UPCOMING(2586, null, null),
```
Comment (Nightenom) [inline src/main/java/com/ldtteam/structures/blueprints/v1/DataVersion.java]:
```suggestion
    UPCOMING(2587, null, null),
```

File: src/main/java/com/ldtteam/structurize/Structurize.java [hunk 3]
```diff
@@ -42,9 +44,23 @@ public Structurize()
         Mod.EventBusSubscriber.Bus.FORGE.bus().get().register(EventSubscriber.class);
         DistExecutor.unsafeRunWhenOn(Dist.CLIENT, () -> () -> Mod.EventBusSubscriber.Bus.FORGE.bus().get().register(ClientEventSubscriber.class));
 
-        if (DataVersion.CURRENT == DataVersion.UPCOMING)
+        if (DataFixesManager.getDataFixer() instanceof com.mojang.datafixers.DataFixerUpper)
```
Comment (Nightenom) [inline src/main/java/com/ldtteam/structurize/Structurize.java]: Can you move that into DataFixerUtils as static boolean and display text in buildtool (like the escape one)?

File: src/main/java/com/ldtteam/structurize/Structurize.java [hunk 4]
```diff
@@ -42,9 +44,23 @@ public Structurize()
...
         {
-            throw new RuntimeException("Missing some newest data versions. Please update com/ldtteam/structures/blueprints/v1/DataVersion");
+            if (DataFixesManager.getDataFixer().getSchema(Integer.MAX_VALUE - 10).getVersionKey() >= DataVersion.UPCOMING.getDataVersion())
+            {
+                throw new RuntimeException("Missing some newest data versions. Please update com/ldtteam/structures/blueprints/v1/DataVersion");
+            }
+            else if (DataVersion.CURRENT == DataVersion.UPCOMING)
```
Comment (Nightenom) [inline src/main/java/com/ldtteam/structurize/Structurize.java]:
```suggestion
            else if (!FMLEnvironment.production && DataVersion.CURRENT == DataVersion.UPCOMING)
```

File: src/main/java/com/ldtteam/structurize/Structurize.java [hunk 5]
```diff
@@ -42,9 +44,23 @@ public Structurize()
         Mod.EventBusSubscriber.Bus.FORGE.bus().get().register(EventSubscriber.class);
         DistExecutor.unsafeRunWhenOn(Dist.CLIENT, () -> () -> Mod.EventBusSubscriber.Bus.FORGE.bus().get().register(ClientEventSubscriber.class));
 
-        if (DataVersion.CURRENT == DataVersion.UPCOMING)
+        if (DataFixesManager.getDataFixer() instanceof com.mojang.datafixers.DataFixerUpper)
         {
-            throw new RuntimeException("Missing some newest data versions. Please update com/ldtteam/structures/blueprints/v1/DataVersion");
+            if (DataFixesManager.getDataFixer().getSchema(Integer.MAX_VALUE - 10).getVersionKey() >= DataVersion.UPCOMING.getDataVersion())
+            {
+                throw new RuntimeException("Missing some newest data versions. Please update com/ldtteam/structures/blueprints/v1/DataVersion");
```
Comment (Nightenom) [inline src/main/java/com/ldtteam/structurize/Structurize.java]: or something like that, the first sentence can be as long as `Missing some newest data versions. Please update` and should tell players to check their versions
```suggestion
                throw new RuntimeException("You are trying to run old mod on much newer vanilla. Missing some newest data versions. Please update com/ldtteam/structures/blueprints/v1/DataVersion");
```

File: src/main/java/com/ldtteam/structurize/Structurize.java [hunk 6]
```diff
@@ -42,9 +44,23 @@ public Structurize()
         Mod.EventBusSubscriber.Bus.FORGE.bus().get().register(EventSubscriber.class);
         DistExecutor.unsafeRunWhenOn(Dist.CLIENT, () -> () -> Mod.EventBusSubscriber.Bus.FORGE.bus().get().register(ClientEventSubscriber.class));
 
-        if (DataVersion.CURRENT == DataVersion.UPCOMING)
+        if (DataFixesManager.getDataFixer() instanceof com.mojang.datafixers.DataFixerUpper)
         {
-            throw new RuntimeException("Missing some newest data versions. Please update com/ldtteam/structures/blueprints/v1/DataVersion");
+            if (DataFixesManager.getDataFixer().getSchema(Integer.MAX_VALUE - 10).getVersionKey() >= DataVersion.UPCOMING.getDataVersion())
```
Comment (Nightenom) [inline src/main/java/com/ldtteam/structurize/Structurize.java]: Have you checked it works as intended (cuz I just made that code out of my head without further checking it actually does what I think it should do)?

**Review by Nightenom — CHANGES_REQUESTED** [review]

File: src/main/resources/assets/structurize/lang/en_us.json [hunk 7]
```diff
@@ -1152,4 +1152,5 @@
   "block.structurize.horizontal_plain_cactus_birch_timber_frame": "Plain Horizontal Cactus Birch Timber Frame",
   "structurize.gui.buildtool.creative_only": "Structurize does not support using the build tool when in survival. Switch to creative or install MineColonies and use the MineColonies Builder.",
   "structurize.gui.replaceblock.ambiguous_properties": "Transformation from %s to %s is ambiguous because the following properties are not present in the source block: %s"
```
Comment (ravenbuilder934) [inline src/main/resources/assets/structurize/lang/en_us.json]:
```suggestion
  "structurize.gui.replaceblock.ambiguous_properties": "Transformation from %s to %s is ambiguous because the following properties are not present in the source block: %s",
```
Forgot a comma there

File: src/main/resources/assets/structurize/lang/en_us.json [hunk 8]
```diff
@@ -1152,4 +1152,5 @@
...
+  "structurize.gui.buildtool.unexpecteddatafixer": "Invalid datafixer detected, unpredicted side-effects possible, check log for more info!"
```
Comment (ravenbuilder934) [inline src/main/resources/assets/structurize/lang/en_us.json]:
```suggestion
  "structurize.gui.buildtool.unexpecteddatafixer": "Invalid datafixer detected! Unpredicted side effects are possible! Check the log for more info."
```

**Review by ravenbuilder934 — CHANGES_REQUESTED** [review]

File: src/main/resources/assets/structurize/lang/en_us.json (hunk 8 above)
Comment (sciwhiz12) [reply src/main/resources/assets/structurize/lang/en_us.json]: `Unpredictable side effects are possible!`

File: src/main/java/com/ldtteam/structurize/Structurize.java [hunk 9]
```diff
@@ -42,9 +46,23 @@ public Structurize()
         Mod.EventBusSubscriber.Bus.FORGE.bus().get().register(EventSubscriber.class);
         DistExecutor.unsafeRunWhenOn(Dist.CLIENT, () -> () -> Mod.EventBusSubscriber.Bus.FORGE.bus().get().register(ClientEventSubscriber.class));
 
-        if (DataVersion.CURRENT == DataVersion.UPCOMING)
+        if (DataFixerUtils.isVanillaDF)
         {
-            throw new RuntimeException("Missing some newest data versions. Please update com/ldtteam/structures/blueprints/v1/DataVersion");
+            if (DataFixesManager.getDataFixer().getSchema(Integer.MAX_VALUE - 10).getVersionKey() >= DataVersion.UPCOMING.getDataVersion())
+            {
+                throw new RuntimeException("You are trying to run old mod on much newer vanilla. Missing some newest data versions. Please update com/ldtteam/structures/blueprints/v1/DataVersion");
```
Comment (sciwhiz12) [inline src/main/java/com/ldtteam/structurize/Structurize.java:53]:
```suggestion
                throw new RuntimeException("You are trying to run on a much newer game version than supported by this version of the mod. Missing some newest data versions, please update com/ldtteam/structures/blueprints/v1/DataVersion");
```
Could also remove the part that mentions the data versions and class, and just a generic "please update this mod." message (since it may confuse users).

File: src/main/resources/assets/structurize/lang/en_us.json (hunk 8 above)
Comment (Raycoms) [reply src/main/resources/assets/structurize/lang/en_us.json]: Needed to cut Unpredictable because of no space. It's now "Side-effects are possible

**Review by Nightenom — APPROVED** [review]

**Review by marchermans — APPROVED** [review]
