### PR TITLE
Rotation Crash on TagSubstitutionBlock

### LINKED ISSUE #813: Structurize crash when rotating decoration
### Is there an existing issue for this?

- [x] I have searched the existing issues.

### Are you using the latest Structurize Version?

- [x] I am running the latest **beta/release** version of Structurize for my Minecraft version.
I am also running the latest versions of other mods that are part of my problem.

### Did you check on the Wiki? or ask on Discord?

- [x] I checked the MineColonies/Structurize [Wiki](https://wiki.minecolonies.ldtteam.com/) or I asked on [discord](https://discord.minecolonies.com/).

### Minecraft Version

1.21

### Structurize Version

1.0.802

### MineColonies Version (if related bug)

1.1.1242

### Related Mods and their Versions

Blockui 1.0.208
Neoforge 21.1.217
Biomes O Plenty 21.1.0.13 (note, BoP items are not used in the exact schematic that is crashing, but the style requires this mod, or it will be hidden)
Ars Nouveau 5.11.1
Archwood Collective stylepack from https://www.planetminecraft.com/project/archwood-collective-minecolonies-style-1-21/  (version is 19)

### Current Behavior

Crash when rotating decoration schematic.

### Expected Behavior

No crash.

### Reproduction Steps

1. Create a colony.
2. Ensure you have a functioning builder (probably not needed for the repro)
3. Ensure you have Archwood Collective 1.21.1 style installed. This requires BoP and Ars nouveau. Versions of those mods are listed in related mods.
4. Using build tool (I was in creative), inside the colony, bring up preview of decorations/sourcegeneration/berryburntile.
5. Rotate (or mirror, according to another user). I did it with the keystrokes, I assume it'll bug for any rotation.
6. Crash

### Logs

https://gist.github.com/Shadizar/296959ac2078d51565f8676734fdc4fa

### Anything else?

[21Jan2026 17:34:04.816] [Render thread/ERROR] [net.minecraft.client.Minecraft/FATAL]: Reported exception thrown!
net.minecraft.ReportedException: KeyPressed event for BO screen
	at TRANSFORMER/minecraft@1.21.1/net.minecraft.client.gui.screens.Screen.wrapScreenError(Screen.java:456) ~[client-1.21.1-20240808.144430-srg.jar%23618!/:?]
	at TRANSFORMER/minecraft@1.21.1/net.minecraft.client.KeyboardHandler.keyPress(KeyboardHandler.java:407) ~[client-1.21.1-20240808.144430-srg.jar%23618!/:?]
	at TRANSFORMER/minecraft@1.21.1/net.minecraft.client.KeyboardHandler.lambda$setup$8(KeyboardHandler.java:515) ~[client-1.21.1-20240808.144430-srg.jar%23618!/:?]
	at TRANSFORMER/minecraft@1.21.1/net.minecraft.util.thread.BlockableEventLoop.execute(BlockableEventLoop.java:98) ~[client-1.21.1-20240808.144430-srg.jar%23618!/:?]
	at TRANSFORMER/minecraft@1.21.1/net.minecraft.client.KeyboardHandler.lambda$setup$9(KeyboardHandler.java:515) ~[client-1.21.1-20240808.144430-srg.jar%23618!/:?]
	at MC-BOOTSTRAP/org.lwjgl.glfw@3.3.3+5/org.lwjgl.glfw.GLFWKeyCallbackI.callback(GLFWKeyCallbackI.java:44) ~[lwjgl-glfw-3.3.3.jar%23173!/:build 5]
	at MC-BOOTSTRAP/org.lwjgl@3.3.3+5/org.lwjgl.system.JNI.invokeV(Native Method) ~[lwjgl-3.3.3.jar%23185!/:build 5]
	at MC-BOOTSTRAP/org.lwjgl.glfw@3.3.3+5/org.lwjgl.glfw.GLFW.glfwWaitEventsTimeout(GLFW.java:3509) ~[lwjgl-glfw-3.3.3.jar%23173!/:build 5]
	at TRANSFORMER/minecraft@1.21.1/com.mojang.blaze3d.systems.RenderSystem.limitDisplayFPS(RenderSystem.java:162) ~[client-1.21.1-20240808.144430-srg.jar%23618!/:?]
	at TRANSFORMER/minecraft@1.21.1/net.minecraft.client.Minecraft.runTick(Minecraft.java:1220) ~[client-1.21.1-20240808.144430-srg.jar%23618!/:?]
	at TRANSFORMER/minecraft@1.21.1/net.minecraft.client.Minecraft.run(Minecraft.java:807) ~[client-1.21.1-20240808.144430-srg.jar%23618!/:?]
	at TRANSFORMER/minecraft@1.21.1/net.minecraft.client.main.Main.main(Main.java:230) ~[client-1.21.1-20240808.144430-srg.jar%23618!/:?]
	at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103) ~[?:?]
	at java.base/java.lang.reflect.Method.invoke(Method.java:580) ~[?:?]
	at MC-BOOTSTRAP/fml_loader@4.0.42/net.neoforged.fml.loading.targets.CommonLaunchHandler.runTarget(CommonLaunchHandler.java:136) ~[loader-4.0.42.jar%23107!/:4.0]
	at MC-BOOTSTRAP/fml_loader@4.0.42/net.neoforged.fml.loading.targets.CommonLaunchHandler.clientService(CommonLaunchHandler.java:124) ~[loader-4.0.42.jar%23107!/:4.0]
	at MC-BOOTSTRAP/fml_loader@4.0.42/net.neoforged.fml.loading.targets.CommonClientLaunchHandler.runService(CommonClientLaunchHandler.java:32) ~[loader-4.0.42.jar%23107!/:4.0]
	at MC-BOOTSTRAP/fml_loader@4.0.42/net.neoforged.fml.loading.targets.CommonLaunchHandler.lambda$launchService$4(CommonLaunchHandler.java:118) ~[loader-4.0.42.jar%23107!/:4.0]
	at MC-BOOTSTRAP/cpw.mods.modlauncher@11.0.5/cpw.mods.modlauncher.LaunchServiceHandlerDecorator.launch(LaunchServiceHandlerDecorator.java:30) [modlauncher-11.0.5.jar%23112!/:?]
	at MC-BOOTSTRAP/cpw.mods.modlauncher@11.0.5/cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:53) [modlauncher-11.0.5.jar%23112!/:?]
	at MC-BOOTSTRAP/cpw.mods.modlauncher@11.0.5/cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:71) [modlauncher-11.0.5.jar%23112!/:?]
	at MC-BOOTSTRAP/cpw.mods.modlauncher@11.0.5/cpw.mods.modlauncher.Launcher.run(Launcher.java:103) [modlauncher-11.0.5.jar%23112!/:?]
	at MC-BOOTSTRAP/cpw.mods.modlauncher@11.0.5/cpw.mods.modlauncher.Launcher.main(Launcher.java:74) [modlauncher-11.0.5.jar%23112!/:?]
	at MC-BOOTSTRAP/cpw.mods.modlauncher@11.0.5/cpw.mods.modlauncher.BootstrapLaunchConsumer.accept(BootstrapLaunchConsumer.java:26) [modlauncher-11.0.5.jar%23112!/:?]
	at MC-BOOTSTRAP/cpw.mods.modlauncher@11.0.5/cpw.mods.modlauncher.BootstrapLaunchConsumer.accept(BootstrapLaunchConsumer.java:23) [modlauncher-11.0.5.jar%23112!/:?]
	at cpw.mods.bootstraplauncher@2.0.2/cpw.mods.bootstraplauncher.BootstrapLauncher.run(BootstrapLauncher.java:210) [bootstraplauncher-2.0.2.jar:?]
	at cpw.mods.bootstraplauncher@2.0.2/cpw.mods.bootstraplauncher.BootstrapLauncher.main(BootstrapLauncher.java:69) [bootstraplauncher-2.0.2.jar:?]
Caused by: java.lang.ArrayIndexOutOfBoundsException: Index 2 out of bounds for length 2
	at TRANSFORMER/structurize@1.0.802-1.21.1-snapshot/com.ldtteam.structurize.component.CapturedBlock.applyRotationMirror(CapturedBlock.java:81) ~[structurize-1.0.802-1.21.1-snapshot.jar%23989!/:1.0.802-1.21.1-snapshot]
	at TRANSFORMER/structurize@1.0.802-1.21.1-snapshot/com.ldtteam.structurize.blueprints.v1.Blueprint.setRotationMirrorRelative(Blueprint.java:727) ~[structurize-1.0.802-1.21.1-snapshot.jar%23989!/:1.0.802-1.21.1-snapshot]
	at TRANSFORMER/structurize@1.0.802-1.21.1-snapshot/com.ldtteam.structurize.blueprints.v1.Blueprint.setRotationMirror(Blueprint.java:640) ~[structurize-1.0.802-1.21.1-snapshot.jar%23989!/:1.0.802-1.21.1-snapshot]
	at TRANSFORMER/structurize@1.0.802-1.21.1-snapshot/com.ldtteam.structurize.storage.rendering.types.BlueprintPreviewData.applyRotationMirrorAndSync(BlueprintPreviewData.java:329) ~[structurize-1.0.802-1.21.1-snapshot.jar%23989!/:1.0.802-1.21.1-snapshot]
	at TRANSFORMER/structurize@1.0.802-1.21.1-snapshot/com.ldtteam.structurize.storage.rendering.types.BlueprintPreviewData.rotate(BlueprintPreviewData.java:244) ~[structurize-1.0.802-1.21.1-snapshot.jar%23989!/:1.0.802-1.21.1-snapshot]
	at TRANSFORMER/structurize@1.0.802-1.21.1-snapshot/com.ldtteam.structurize.client.gui.AbstractBlueprintManipulationWindow.rotateRightClicked(AbstractBlueprintManipulationWindow.java:523) ~[structurize-1.0.802-1.21.1-snapshot.jar%23989!/:1.0.802-1.21.1-snapshot]
	at TRANSFORMER/structurize@1.0.802-1.21.1-snapshot/com.ldtteam.structurize.client.gui.AbstractBlueprintManipulationWindow.onUnhandledKeyTyped(AbstractBlueprintManipulationWindow.java:301) ~[structurize-1.0.802-1.21.1-snapshot.jar%23989!/:1.0.802-1.21.1-snapshot]
	at TRANSFORMER/blockui@1.0.208-1.21.1-snapshot/com.ldtteam.blockui.views.BOWindow.onKeyTyped(BOWindow.java:213) ~[blockui-1.0.208-1.21.1-snapshot.jar%23665!/:1.0.208-1.21.1-snapshot]
	at TRANSFORMER/blockui@1.0.208-1.21.1-snapshot/com.ldtteam.blockui.BOScreen.keyPressed(BOScreen.java:154) ~[blockui-1.0.208-1.21.1-snapshot.jar%23665!/:1.0.208-1.21.1-snapshot]
	at TRANSFORMER/minecraft@1.21.1/net.minecraft.client.KeyboardHandler.lambda$keyPress$5(KeyboardHandler.java:411) ~[client-1.21.1-20240808.144430-srg.jar%23618!/:?]
	at TRANSFORMER/minecraft@1.21.1/net.minecraft.client.gui.screens.Screen.wrapScreenError(Screen.java:451) ~[client-1.21.1-20240808.144430-srg.jar%23618!/:?]
	... 26 more
[21Jan2026 17:34:05.703] [Server thread/INFO] [MapFrontiers/]: ServerStoppingEvent done

### Footer

---
## Viewers
* Add a thumbs-up to the bug report if you are also affected. This helps the bug report become more visible to the team and doesn't clutter the comments.
* Add a comment if you have any insights or background information that isn't already part of the conversation.

### PR DESCRIPTION
**Pull request by armele**
Closes #813

# Changes proposed in this pull request
- Changed the logic around the rotation of the TagSubstitutionBlock to avoid the crash reported in #813 

## Testing
- [X] Yes I tested this before submitting it.
- [ ] I also did a multiplayer test.

I was able to reproduce the crash and confirm that after the fix it was eliminated.
I did a number of other tests using the TagSubstitutionBlock.  I did note that if the TSB is put on a chest that the rotation of the chest was NOT correctly reflected (the position was, but not the facing).  I did confirm that contents were persisted as well.

After a number of attempts to explore fixes, I decided to submit this small improvement (no crash) despite the lack of proper chest orientation post-rotation.

Review please

### CODE REVIEW

File: src/main/java/com/ldtteam/structurize/component/CapturedBlock.java [hunk 1]
```diff
@@ -67,22 +67,40 @@ public CapturedBlock(final BlockState blockState,
...
+
+        // No BE data: just rotate the state.
         if (serializedBE.isEmpty())
         {
-            return new CapturedBlock(rotationMirror.applyToBlockState(blockState), serializedBE, itemStack);
+            return new CapturedBlock(rotatedState, serializedBE, itemStack);
         }
 
+        // If the rotated state cannot host a BE, drop any BE tag (prevents renderer/loader issues).
+        if (!rotatedState.hasBlockEntity())
```
Comment (Raycoms) [inline src/main/java/com/ldtteam/structurize/component/CapturedBlock.java:80]: Can it happen that we get serializedBE not empty but it has no block entity?

Comment (armele) [reply src/main/java/com/ldtteam/structurize/component/CapturedBlock.java:80]: What I saw when debugging was that for this specific decoration the block entity was reported as "present but blank" - showed up as "{}" when dumping the logs. Not sure _how_ that comes about... but wanted to guard against it.

Comment (Raycoms) [reply src/main/java/com/ldtteam/structurize/component/CapturedBlock.java:80]: Might be interesting to log that then

**Comment by Shadizar** [comment]
Hi Armele, any hope for this one?  I'm worried players of my style may be hitting this still

**Comment by armele** [comment]
Added logging per code review feedback.  Re-tested.
Before fix - crash upon rotation.
After fix - rotation successful, log contains:
[12Mar2026 11:57:13.007] [Render thread/WARN][structurize/]: Block Block{minecraft:grass_block}[snowy=false] is not empty, but has no block entity.

**Review by Raycoms — APPROVED** [review]

**Review by someaddons — APPROVED** [review]

**Comment by Raycoms** [comment]
Please port

**Comment by armele** [comment]
I actually don't think we need to port this one - the defect report indicated it was only affecting 1.21.1.
